export interface Establishment {
    id?: number,
    name: string,
    site: string,
    address: string,
    numberr: string,
    cep: string,
    email: string,
    tel: string,
    cel: string,
    district: string,
    city: string,
    state: string,
    category: string,
    imgurl: string,
    description: string,
    score: number,
    actived: boolean,
    dataest?: Date 
}
